"""initial schema

Revision ID: 1b98d91c03cc
Revises: 
Create Date: 2026-08-06 15:43:34.714278

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1b98d91c03cc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=15), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(length=15), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(length=15), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('first_name'),
    sa.UniqueConstraint('username')
    )
    op.create_table('boards',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('owner_uid', sa.UUID(), nullable=True),
    sa.Column('board_title', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('board_description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('public', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['owner_uid'], ['users.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('audits',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('user_uid', sa.UUID(), nullable=True),
    sa.Column('board_uid', sa.UUID(), nullable=True),
    sa.Column('target_uid', sa.UUID(), nullable=True),
    sa.Column('action', sa.Enum('BOARD_CREATED', 'BOARD_UPDATED', 'BOARD_ARCHIVED', 'BOARD_DUPLICATED', 'BOARD_DELETED', 'MEMBER_ADDED', 'MEMBER_REMOVED', 'MEMBER_ROLE_CHANGED', 'MEMBER_LEFT', 'REQUEST_SENT', 'REQUEST_APPROVED', 'REQUEST_REJECTED', 'INVITE_SENT', 'INVITE_ACCEPTED', 'INVITE_REVOKED', name='auditaction'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['board_uid'], ['boards.uid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_uid'], ['users.uid'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_uid'], ['users.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('boardusers',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('user_uid', sa.UUID(), nullable=True),
    sa.Column('board_uid', sa.UUID(), nullable=True),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'MEMBER', name='userrole'), nullable=False),
    sa.ForeignKeyConstraint(['board_uid'], ['boards.uid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_uid'], ['users.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('invitations',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('user_uid', sa.UUID(), nullable=True),
    sa.Column('recipient_uid', sa.UUID(), nullable=True),
    sa.Column('board_uid', sa.UUID(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('accepted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['board_uid'], ['boards.uid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_uid'], ['users.uid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_uid'], ['users.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('notifications',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('user_uid', sa.UUID(), nullable=True),
    sa.Column('board_uid', sa.UUID(), nullable=True),
    sa.Column('message_content', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('message_type', sa.Enum('REQUEST_RECEIVED', 'REQUEST_APPROVED', 'REQUEST_REJECTED', 'INVITE_RECEIVED', 'INVITE_ACCEPTED', 'MEMBER_REMOVED', 'ROLE_CHANGED', 'BOARD_ARCHIVED', 'MESSAGE_RECEIVED', name='notificationtype'), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['board_uid'], ['boards.uid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_uid'], ['users.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('requests',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('user_uid', sa.UUID(), nullable=True),
    sa.Column('board_uid', sa.UUID(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'EXPIRED', name='requeststatus'), nullable=False),
    sa.ForeignKeyConstraint(['board_uid'], ['boards.uid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_uid'], ['users.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('requests')
    op.drop_table('notifications')
    op.drop_table('invitations')
    op.drop_table('boardusers')
    op.drop_table('audits')
    op.drop_table('boards')
    op.drop_table('users')
    # ### end Alembic commands ###
